# Generated by Django 5.1.4 on 2025-01-06 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assemblies', to='aircrafts.aircraft')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assemblies', to='parts.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wing', 'Wing'), ('fuselage', 'Fuselage'), ('tail', 'Tail'), ('avionics', 'Avionics')], max_length=8, unique=True)),
                ('compatible_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraftmodel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.partmodel'),
        ),
        migrations.CreateModel(
            name='PartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(blank=True, default=0)),
                ('part_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.partmodel')),
            ],
        ),
    ]
