# Generated by Django 5.1.4 on 2025-01-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='name',
            field=models.CharField(choices=[('wing', 'Wing'), ('fuselage', 'Fuselage'), ('tail', 'Tail'), ('avionics', 'Avionics')], max_length=8),
        ),
    ]
