# Generated by Django 5.1.4 on 2025-01-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partstock',
            name='part_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.partmodel', unique=True),
        ),
    ]
