# Generated by Django 5.1.4 on 2025-01-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_partstock_part_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partstock',
            name='part_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts.partmodel'),
        ),
    ]
