# Generated by Django 5.1.4 on 2025-01-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_partmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_assembled',
            field=models.BooleanField(default=False),
        ),
    ]
