# Generated by Django 5.1.4 on 2025-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_partstock_part_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='is_assembled',
        ),
        migrations.AddField(
            model_name='part',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
