# Generated by Django 5.1.4 on 2025-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_remove_part_is_assembled_part_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmodel',
            name='slug',
            field=models.SlugField(choices=[('wing', 'Wing'), ('fuselage', 'Fuselage'), ('tail', 'Tail'), ('avionics', 'Avionics'), ('assembly', 'Assembly')], null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
