# Generated by Django 5.1.4 on 2025-01-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_partmodel_slug_alter_partmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='slug',
            field=models.SlugField(choices=[('wing', 'Wing'), ('fuselage', 'Fuselage'), ('tail', 'Tail'), ('avionics', 'Avionics'), ('assembly', 'Assembly')], null=True),
        ),
    ]
