# Generated by Django 5.1.4 on 2025-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_partmodel_name_alter_partmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='slug',
            field=models.SlugField(choices=[('wing', 'Wing'), ('fuselage', 'Fuselage'), ('tail', 'Tail'), ('avionics', 'Avionics')], null=True),
        ),
    ]
