# Generated by Django 5.1.4 on 2025-01-07 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'Akinci'), ('kizilelma', 'Kizilelma')], max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('production_completed', models.BooleanField(default=False)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.aircraftmodel')),
            ],
        ),
    ]
