# Generated by Django 5.1.4 on 2025-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('wing', 'Wing Team'), ('fuselage', 'Fuselage Team'), ('tail', 'Tail Team'), ('avionics', 'Avionics Team'), ('assembly', 'Assembly Team')], max_length=50),
        ),
    ]
